language: bash
jdk: oraclejdk8
sudo: required
dist: trusty
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
script:
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  # Add gcloud to $PATH
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version
  - gcloud auth activate-service-account --key-file=credentials.json
  - gcloud config set project app-chat-98f8b
  - gcloud firebase test android run --type instrumentation --test ./app-debug-androidTest.apk --app ./Radium-v1.9.0.apk --device model=Nexus6,version=25,locale=en,orientation=portrait 
branches:
  only:
  - master
git:
  depth: 50